name: Sporcafe Bot Guncelle

on:
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir otomatik çalışır
  workflow_dispatch:      # Manuel çalıştırma butonu
  push:                   # Kodda değişiklik yapınca çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install requests

      - name: Botu Calistir
        run: python main.py

      - name: Kaydet ve Yukle
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add Sporcafe.m3u
          git commit -m "Sporcafe Liste Guncellendi: $(date)" || exit 0
          git push
